name: Build App

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g. v1.0.0)"
        required: true
        type: string

jobs:
  build:
    runs-on: windows-11-arm

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repo: amir1376/ab-download-manager
          ref: ${{ github.event.inputs.tag }}

      - name: Download JBR
        run: |
          curl -L -o jbr.zip "https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-21.0.8-windows-aarch64-b895.146.zip"
          mkdir jbr
          tar -xf jbr.zip -C jbr --strip-components=1

      - name: Set JAVA_HOME and update PATH
        run: |
          echo "JAVA_HOME=${{ github.workspace }}\\jbr" >> $env:GITHUB_ENV
          echo "${{ github.workspace }}\\jbr\\bin" >> $env:GITHUB_PATH

      - name: Verify Java
        run: java -version

      - name: Ensure gradlew is executable
        run: git update-index --chmod=+x gradlew

      - name: Run Gradle task
        run: .\gradlew createReleaseFolderForCi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-release
          path: build/ci-release
